# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml

{{- define "alist-tvbox.app.hardcodedValues" -}}

global:
  fullnameOverride: alist-tvbox

defaultPodOptions:
  hostname: alist-tvbox

controllers:
  main:
    enabled: true
    containers:
      main:
        image:
          repository: haroldli/xiaoya-tvbox
          tag: latest
          pullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: ALIST_PORT
          value: "80"
        
        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: true
            # -- Set this to `true` if you wish to specify your own livenessProbe
            custom: true
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # -- The spec field contains the values for the default livenessProbe.
            # If you selected `custom: true`, this field holds the definition of the livenessProbe.
            # @default -- See below
            spec:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 300
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3

          # -- Redainess probe configuration
          # @default -- See below
          readiness:
            # -- Enable the readiness probe
            enabled: true
            # -- Set this to `true` if you wish to specify your own readinessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # type: TCP
            # -- The spec field contains the values for the default readinessProbe.
            # If you selected `custom: true`, this field holds the definition of the readinessProbe.
            # @default -- See below
            # spec:
            #   initialDelaySeconds: 0
            #   periodSeconds: 10
            #   timeoutSeconds: 1
            #   failureThreshold: 3

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      admin:
        enabled: true
        primary: true
        port: 4567
        protocol: HTTP
      http:
        enabled: true
        primary: false
        port: 80
        protocol: HTTP

persistence:
  pvc:
    enabled: true
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 128Mi
    advancedMounts:
      main:
        main:
          - path: /data
            readOnly: false

{{- end }}

{{ if .Values.app.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "app" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "alist-tvbox.app.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{- include "alist-tvbox.scheduledRestart" . }}
{{ end }}
