{{- if .Values.ingress.enabled -}}
{{- $fullName := include "http-libchart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.tls .Values.ingress.traekfikForceHTTPS -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-%s" (include "http-libchart.fullname" .) "http-redirect" }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
{{- end }}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if and .Values.ingress.tls .Values.ingress.certManagerClusterIssuerName -}}
  {{- $_ := set .Values.ingress.annotations "cert-manager.io/cluster-issuer" .Values.ingress.certManagerClusterIssuerName }}
{{- end }}
{{- if and .Values.ingress.tls .Values.ingress.traekfikForceHTTPS -}}
  {{- $_ := set .Values.ingress.annotations "traefik.ingress.kubernetes.io/router.middlewares"  (printf "%s-%s-%s" .Release.Namespace (include "http-libchart.fullname" .) "http-redirect@kubernetescrd") }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "http-libchart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: alist-tvbox.niyoh.top
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.adminPort }}
    - host: xiaoya.niyoh.top
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.xiaoyaPort }}
{{- end }}