apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-libchart.fullname" . }}
  labels:
    {{- include "http-libchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.service.xiaoyaPort }}
      targetPort: xiaoya
      protocol: TCP
      name: xiaoya
  selector:
    {{- include "http-libchart.selectorLabels" . | nindent 4 }}