apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-system
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - sonarr.niyoh.top
        - radarr.niyoh.top
        - prowlarr.niyoh.top
        - jellyseerr.niyoh.top
        - jproxy.niyoh.top
        - chsub.niyoh.top
      secretName: misc-niyoh-top-tls
  rules:
    - host: sonarr.niyoh.top
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service
                port:
                  name: sonarr-http
    - host: radarr.niyoh.top
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service
                port:
                  name: radarr-http
    - host: prowlarr.niyoh.top
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service
                port:
                  name: prowlarr-http
    - host: jellyseerr.niyoh.top
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service
                port:
                  name: jellyseerr-http
    - host: jproxy.niyoh.top
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service
                port:
                  name: jproxy-http
    - host: chsub.niyoh.top
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: service
                port:
                  name: chsub-http
