apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "A valid .pvc.name required!" .Values.pvc.name }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.pvc.storageClassName | default "local-path" }}
  resources:
    requests:
      storage: {{ required "A valid .pvc.storageSize required!" .Values.pvc.storageSize }}