# Default values for go-chatgpt-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: true
  className: traefik
  certManagerClusterIssuerName: ""
  annotations:
    traefik.ingress.kubernetes.io/custom-response-headers: Access-Control-Allow-Origin=*,Access-Control-Allow-Methods=GET,POST,PUT,DELETE,OPTIONS,Access-Control-Allow-Headers=Content-Type,Authorization,X-Requested-With
  hosts:
    - host: go-chatgpt-api.niyoh.top
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}