app:
  enabled: true

  controllers:
    main:
      containers:
        main:
          env:
            TZ: Asia/Shanghai
            BOT_TOKEN: bot-token
            GUILD_ID: "123456"
            COZE_BOT_ID: "123456"
            CHANNEL_ID: "123456"
            PROXY_SECRET: sk-xxxx