apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-libchart.fullname" . }}
  labels:
    {{- include "http-libchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: qb-tcp
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: qb-udp
  selector:
    {{- include "http-libchart.selectorLabels" . | nindent 4 }}