apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aria2.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}