# Default values for alist-tvbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: haroldli/xiaoya-tvbox
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  env:
    - name: TZ
      value: Asia/Shanghai
    - name: ALIST_PORT
      value: "80"

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  adminPort: 4567
  xiaoyaPort: 80

ingress:
  enabled: true
  className: traefik
  certManagerClusterIssuerName: ""
  traekfikForceHTTPS: true
  annotations: {}
  tls:
    - secretName: alist-tvbox-tls-secret
      hosts:
        - alist-tvbox.niyoh.top
        - xiaoya.niyoh.top

resources:
  {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

pvc:
  name: alist-tvbox-pvc
  storageSize: 128Mi

volumes:
  - name: alist-tvbox-storage
    persistentVolumeClaim:
      claimName: alist-tvbox-pvc

volumeMounts:
  - mountPath: /data
    name: alist-tvbox-storage

scheduledRestart:
  schedule: "0 4 * * *"