# Default values for alist-xiaoya.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

aliYunDriveToken: 
aliYunDriveOpenToken: 
aliYunDriveTempFolderID: 

alistAuthToken:
dockerAddress: http://xiaoya.niyoh.top

replicaCount: 1

image:
  repository: xiaoyaliu/alist
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  certManagerClusterIssuerName: ""
  traekfikForceHTTPS: true
  annotations: {}
  hosts:
    - host: xiaoya.niyoh.top
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: alist-xiaoya-tls-secret
     hosts:
       - xiaoya.niyoh.top

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

volumes:
  - name: alist-xiaoya-storage
    emptyDir: {}

volumeMounts:
  - name: alist-xiaoya-storage
    mountPath: /data

scheduledRestart:
  schedule: "0 4 * * *"