# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml

{{- define "lx-source.app.hardcodedValues" -}}

global:
  fullnameOverride: lx-source

defaultPodOptions:
  hostname: lx-source

controllers:
  main:
    enabled: true
    initContainers:
      init:
        image:
          repository: busybox
          tag: latest
        command: ["sh", "-c", "cp -n /configmap/conf.ini /app/data/conf.ini"]
    containers:
      main:
        image:
          repository: niyoh/lx-source
          tag: latest
          pullPolicy: Always
        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: true
            # -- Set this to `true` if you wish to specify your own livenessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # -- The spec field contains the values for the default livenessProbe.
            # If you selected `custom: true`, this field holds the definition of the livenessProbe.
            # @default -- See below

          # -- Redainess probe configuration
          # @default -- See below
          readiness:
            # -- Enable the readiness probe
            enabled: true
            # -- Set this to `true` if you wish to specify your own readinessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # type: TCP
            # -- The spec field contains the values for the default readinessProbe.
            # If you selected `custom: true`, this field holds the definition of the readinessProbe.
            # @default -- See below
            # spec:
            #   initialDelaySeconds: 0
            #   periodSeconds: 10
            #   timeoutSeconds: 1
            #   failureThreshold: 3

configMaps:
  config:
    # -- Enables or disables the configMap
    enabled: true
    data:
      conf.ini: |-
{{ .Files.Get .Values.config.path | indent 8 }}


persistence:
  data:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /app/data
        readOnly: false
  config:
    enabled: true
    type: configMap
    name: lx-source-config
    advancedMounts:
      main:
        init:
          - path: /configmap
            readOnly: true

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 9011
        protocol: HTTP

ingress:
  main:
    # -- Make this the primary ingress (used in probes, notes, etc...).
    # If there is more than 1 ingress, make sure that only 1 ingress is marked as primary.
    primary: true

    # -- Provide additional annotations which may be required.
    annotations: {}

    # -- Provide additional labels which may be required.
    labels: {}


{{- end }}

{{ if .Values.app.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "app" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "lx-source.app.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{ end }}
