# Default values for alist.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: xhofe/alist
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  env:
    - name: TZ
      value: Asia/Shanghai

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  port: 5244

ingress:
  enabled: true
  className: traefik
  certManagerClusterIssuerName: ""
  traekfikForceHTTPS: true
  annotations: {}
  hosts:
    - host: alist.niyoh.top
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: alist-tls-secret
      hosts:
        - alist.niyoh.top

resources:
  {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

pvc:
  name: alist-pvc
  storageSize: 128Mi

volumes:
  - name: alist-storage
    persistentVolumeClaim:
      claimName: alist-pvc

volumeMounts:
  - mountPath: /opt/alist/data
    name: alist-storage