# Default values for douban-api-rs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/cxfksword/douban-api-rs
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: traefik
  certManagerClusterIssuerName: ""
  traekfikForceHTTPS: true
  annotations: {}
  hosts:
    - host: douban-api.niyoh.top
      paths:
        - path: /
  tls:
    - secretName: douban-api-rs-tls-secret
      hosts:
        - douban-api-rs.niyoh.top

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}