# Default values for reader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hectorqin/reader
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: READER_APP_CACHECHAPTERCONTENT
      value: "true"
    - name: READER_APP_SECURE
      value: "true"
    - name: READER_APP_SECUREKEY
      value: ""
    - name: READER_APP_INVITECODE
      value: ""

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  certManagerClusterIssuerName: ""
  traekfikForceHTTPS: true
  annotations: {}
  hosts:
    - host: reader.niyoh.top
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: reader-tls-secret
      hosts:
        - reader.niyoh.top

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

pvc:
  name: reader-pvc
  storageSize: 256Mi

volumes:
  - name: reader-storage
    persistentVolumeClaim:
      claimName: reader-pvc

volumeMounts:
  - name: reader-storage
    mountPath: /storage
