# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml

{{- define "chatgpt-free-api.app.hardcodedValues" -}}

global:
  fullnameOverride: chatgpt-free-api

defaultPodOptions:
  hostname: chatgpt-free-api

controllers:
  main:
    enabled: true
    containers:
      main:
        image:
          repository: pawanosman/chatgpt
          tag: latest
          pullPolicy: Always

        env:
          PROXY: true
          PROXY_PROTOCOL: http
          PROXY_HOST: localhost
          PROXY_PORT: 8080
            
        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: true
            # -- Set this to `true` if you wish to specify your own livenessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # -- The spec field contains the values for the default livenessProbe.
            # If you selected `custom: true`, this field holds the definition of the livenessProbe.
            # @default -- See below

          # -- Redainess probe configuration
          # @default -- See below
          readiness:
            # -- Enable the readiness probe
            enabled: true
            # -- Set this to `true` if you wish to specify your own readinessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # type: TCP
            # -- The spec field contains the values for the default readinessProbe.
            # If you selected `custom: true`, this field holds the definition of the readinessProbe.
            # @default -- See below
            # spec:
            #   initialDelaySeconds: 0
            #   periodSeconds: 10
            #   timeoutSeconds: 1
            #   failureThreshold: 3
      proxy:
        image:
          repository: ghcr.io/sagernet/sing-box
          tag: latest
          pullPolicy: Always
        args: ["-D", "/var/lib/sing-box", "-C", "/etc/sing-box/", "run"]
        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: false
            # -- Set this to `true` if you wish to specify your own livenessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # -- The spec field contains the values for the default livenessProbe.
            # If you selected `custom: true`, this field holds the definition of the livenessProbe.
            # @default -- See below

          # -- Redainess probe configuration
          # @default -- See below
          readiness:
            # -- Enable the readiness probe
            enabled: false
            # -- Set this to `true` if you wish to specify your own readinessProbe
            custom: false
            # -- sets the probe type when not using a custom probe
            # @default -- "TCP"
            # type: TCP
            # -- The spec field contains the values for the default readinessProbe.
            # If you selected `custom: true`, this field holds the definition of the readinessProbe.
            # @default -- See below
            # spec:
            #   initialDelaySeconds: 0
            #   periodSeconds: 10
            #   timeoutSeconds: 1
            #   failureThreshold: 3
            #
configMaps:
  proxy-config:
    # -- Enables or disables the configMap
    enabled: true
    data:
      config.json: {{ .Values.proxyConfig }}

persistence:
  proxy-config:
    enabled: true
    type: configMap
    name: chatgpt-free-api-proxy-config
    advancedMounts:
      main:
        proxy:
          - path: /etc/sing-box/config.json
            readOnly: true
            subPath: config.json

service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 3040
        protocol: HTTP

ingress:
  main:
    # -- Make this the primary ingress (used in probes, notes, etc...).
    # If there is more than 1 ingress, make sure that only 1 ingress is marked as primary.
    primary: true

    # -- Provide additional annotations which may be required.
    annotations: {}

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Set the ingressClass that is used for this ingress.
    className: "traefik"

    ## Configure the hosts for the ingress
    hosts:
        # -- Host address. Helm template can be passed.
      - host: chatgpt-free-api.niyoh.top
        ## Configure the paths for the host
        paths:
          - # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              # This can be an actual service name, or reference a service identifier
              # from this values.yaml
              name: main
              # -- Overrides the service port number reference for this path
              port: http

{{- end }}

{{ if .Values.app.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "app" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "chatgpt-free-api.app.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{ end }}
