app:
  enabled: true

ingress:
  main:
    enabled: true

    # -- Set the ingressClass that is used for this ingress.
    className: traefik

    ## Configure the hosts for the ingress
    hosts:
        # -- Host address. Helm template can be passed.
      - host: lx-source.niyoh.top
        ## Configure the paths for the host
        paths:
          - # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              # This can be an actual service name, or reference a service identifier
              # from this values.yaml
              name: main
              # -- Overrides the service port number reference for this path
              port: http