# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
# https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml

libraryPath: /mnt/images

pvc:
  name: immich-pvc
  storageSize: 10Gi

immich:
  env:
    REDIS_HOSTNAME: ""
    REDIS_PASSWORD: ""
    DB_HOSTNAME: ""
    DB_USERNAME: ""
    DB_DATABASE_NAME: ""
    # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance
    DB_PASSWORD: ""

  image:
    tag: release

  immich:
    persistence:
      # Main data store for all photos shared between different components.
      library:
        # Automatically creating the library volume is not supported by this chart
        # You have to specify an existing PVC to use
        existingClaim: immich-pvc

  server:
    podLabels:
      riotkit.org/volume-syncing-controller: "true"
    enabled: true
    image:
      repository: ghcr.io/immich-app/immich-server
      pullPolicy: Always

  machine-learning:
    enabled: true
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      pullPolicy: Always
    env:
      TRANSFORMERS_CACHE: /cache
    persistence:
      cache:
        enabled: true
        size: 10Gi
        # Optional: Set this to pvc to avoid downloading the ML models every start.
        accessMode: ReadWriteOnce
        storageClass: local-path

  postgresql:
    enabled: false

  redis:
    enabled: false

  typesense:
    enabled: true
    env:
      TYPESENSE_DATA_DIR: /tsdata
      TYPESENSE_API_KEY: immich
    persistence:
      tsdata:
        # Enabling typesense persistence is recommended to avoid slow reindexing
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: local-path

    image:
      repository: typesense/typesense
      tag: 0.24.1
      pullPolicy: Always

  microservices:
    image:
      pullPolicy: Always

  web:
    image:
      pullPolicy: Always

  proxy:
    image:
      pullPolicy: Always

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          # # proxy-body-size is set to 0 to remove the body limit on file uploads
          # nginx.ingress.kubernetes.io/proxy-body-size: "0"
          traefik.ingress.kubernetes.io/router.middlewares: immich-http-redirect@kubernetescrd
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: immich.niyoh.top
            paths:
              - path: /
        tls:
          - secretName: immich-tls-secret
            hosts:
              - immich.niyoh.top
