{{- define "http-libchart.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-libchart.fullname" . }}
  labels:
    {{- include "http-libchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "http-libchart.selectorLabels" . | nindent 4 }}
{{- end }}